### ISSUE TITLE
Release a new tag version with the updated babel version

### ISSUE THREAD

**Issue by jasalguero** [milindalvares/ember-cli-accounting#43]
The PR https://github.com/milindalvares/ember-cli-accounting/pull/41 upgraded the babel version which is done to resolve the Ember Global usage deprecation warning, which block upgrading to Ember 4. But the last tag as of today (2.0.2) doesn't include this change, so the only option is to point directly to the master branch...

**Comment by cibernox** [comment]
Published 2.1.0. Hopefully this helps.

**Comment by jasalguero** [comment]
Thank you!
